.. .. ===============
.. .. Internal Images
.. .. ===============

.. |package_summary| image:: _static/images/sphinxdocs/package_summary.png
.. |module_summary| image:: _static/images/sphinxdocs/module_summary.png
.. |methsum| image:: _static/images/sphinxdocs/method_summary.png
.. |methods_summary| replace:: |methsum| **Methods summary**


.. .. ==========================
.. .. Internal Image Screenshots
.. .. ==========================

.. |wrye| image:: ../../Mopy/bash/images/wrye_monkey_87.jpg

